---
# Here we are using the debian package if debian
- include_vars: "{{ ansible_os_family }}.yml"

- include: common.yml

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: mesos.yml tags=configuration
